---
title: "Authoritative Practices and Collective Validation: Wikidata within the Collaborative Digital Edition of the Greek Anthology"
author: 
- Mathilde Verstraete
- Maxime Guénette 
- Marcello Vitali-Rosati 
keywords: Greek Anthology, Digital Philology, Authority, Wikidata, Collective Intelligence
lang: en
format: pdf
abstract: "As collaborative digital platforms become more common in cultural and Digital Humanities projects, the role of non-experts and their contributions to these platforms is shifting. Platforms such as Wikidata invite a reconsideration of where authority lies: not solely in the hands of experts, but also within a wider community of contributors who bring diverse forms of expertise. This development challenges hierarchies in academic and cultural institutions and raises new questions about validation, trust and collaborative knowledge production. In this paper, we explore these questions through the lens of the *Anthologia Graeca* project, where the integration of Wikidata has become a way of rethinking editorial authority as a shared process."
abstract-title: Abstract
bibliography: ref.bib
csl: chicago-author-date.csl 
---
Keywords: Greek Anthology, Digital Philology, Authority, Wikidata, Collective Intelligence

The management and preservation of research data in the Humanities increasingly raise questions concerning sustainability, accessibility, sharing, and validation. In this context, Wikidata emerges as a powerful and collaborative platform. By challenging traditional models in which researchers act simultaneously as producers and gatekeepers of authority, Wikidata reconfigures these issues and fosters new paradigms of collaborative knowledge production.

Within the framework of Digital Humanities (DH), which often emphasizes open processes, data interoperability and collective engagement, Wikidata functions as a knowledge base, enabling a sort of collective verification and semantic linking of information. Unlike traditional academic publishing, where authority is centralised and often restricted to established institutions or recognised experts, Wikidata operates through a model of continuous, multilingual, and community-base editing that promotes the dissemination of free and accessible knowledge globally. This paradigmatic shift invites a fundamental rethinking of authority, editorial responsibility, and the epistemological foundations of data.

How, then, can *expert-led* projects --- whether developed by academics, government agencies or GLAM institutions (Galleries, Libraries, Archives and Museums) --- work with a generalist platform such as Wikidata to generate new forms of knowledge? How do these hybrid models, which combine scholarly expertise with public participation, challenge traditional boundaries between academic and amateur contributors, and between knowledge production and validation?

In this article, we explore how the infrastructure and logic of Wikidata can be integrated into DH projects, with a focus on the *Anthologia Graeca* (*AG*) project, a collaborative digital edition of the *Greek Anthology*. We begin by situating Wikidata within the broader landscape of DH initiatives. We then turn to *AG* as a case study, analyzing how Wikidata is embedded in the project’s data model --- particularly through our treatment of the keyword "authors" --- and how this integration opens new spaces for knowledge production. Finally, drawing on those concrete examples, we will reflect on the tensions between authority and collective intelligence that shape such initiatives, and the ways in which digital infrastructures can both challenge and extend traditional scholarly practices.

<!--@max: est-ce qu'on a une idée de l'importance des contenus concernant les auteurs anciens sur wikidata ? Si pauvre, notre projet ajoute une plus value importante quali- et quantitativement (?) -->

## Wikidata and Digital Humanities

Since its creation in 2012, Wikidata has gradually become one of the most significant knowledge graphs on the Web. As structured data plays an increasingly central role in the organization, retrieval, and circulation of information online, Wikidata occupies a pivotal position in shaping how knowledge is represented, accessed, shared and reused.

As a result, Wikidata has gained popularity within the field of DH. Although there has been --- and to some extent, continues to be --- skepticism about its quality and potential as a scholarly resource, recent studies have shown that it is now widely adopted across DH projects [@cookUsesWikidataGalleries2019; @zhaoSystematicReviewWikidata2023]. Within this context, it is primarily used as a *content provider* --- a means to access, publish, or disseminate Linked Open Data (LOD) while avoiding many of the technical and financial constraints traditionally associated with the Semantic Web.

For institutions in the GLAM sector, Wikidata serves a somewhat different role and is mainly seen as a *publishing platform* and a *tool for metadata curation*. Because digitization strategies have historically been developed independently from one institution to another, accessibility and discoverability vary widely in the GLAM domain [@fagervingWikidataAuthorityControl2023]. Wikidata is thus used either to publish digital identifiers for cultural heritage objects --- enriched with LOD for the first time --- or to enhance metadata by linking institutional records to Wikidata, improving visibility and interoperability [@candelaSystematicReviewWikidata2024].

Wikidata also plays a *connective role*. Its structure as a knowledge graph and its alignment with LOD principles allow it to act as a bridge between otherwise siloed datasets. By assigning persistent identifiers and promoting alignment across vocabularies and standards, Wikidata enables interoperability between different projects and institutions.

## Wikidata as a linking hub

One of the key benefits of Wikidata, as identified by many DH projects and GLAM institutions, is in its function as a hub for linking heterogeneous external resources and datasets [@neubertWikidataLinkingHub2017]. This is achieved through the creation of external *identifier properties*, which connect entities across different databases to their corresponding Wikidata items.

Take, for example, the case of Megara, an ancient Greek πόλις (*pólis*) located in the northern part of the Isthmus of Corinth. Its Wikidata item ([Q42307600](https://www.wikidata.org/wiki/Q42307600)) is linked to a wide range of sources, including dictionaries, library catalogues and domain-specific databases on Greco-Roman antiquity, such as [Pleiades](https://pleiades.stoa.org/places/570468), [ToposText](https://topostext.org/place/380233PMeg) and [MANTO](https://manto.unh.edu/viewer.p/60/2616/object/6580-9619397). Through such links, Wikidata facilitates seamless cross-referencing and acts as a form of authority control [@fagervingWikidataAuthorityControl2023]. As LOD is designed to enrich data with contextual relationships, it becomes much more efficient to enrich a dataset either directly through Wikidata or through cross-queries across databases all linked to a common Q-item.

Some scholars have gone further, suggesting that Wikidata should not only serve as a hub for linking external identifiers, but should actually function as *the* reference identifier [@vanveenWikidataIdentifierIdentifier2019]. The multiplication of identifiers for the same entity (such as [Megara](https://www.wikidata.org/wiki/Q42307600)) can lead to confusion and poor data reconciliation over time. Adopting Wikidata as a universal identifier could offer several benefits: a unified description model, a single SPARQL endpoint and API for querying, and a sustainable infrastructure for data access and storage.

While this position may seem more radical, it highlights another important aspect of Wikidata's relationship with external resources: that of reciprocal contribution. As demonstrated in a paper on the interaction between Wikidata and VIAF --- a global platform that aggregates name authority files from multiple institutions --- bi-directional comparison and contribution can improve data quality on both sides [@bianchiniVIAFWikidataComplementary2021]. In this way, GLAM institutions such as libraries can not only contribute to Wikidata, but also benefit from it.

## Authority on Digital Platforms

This brings us to a central question: how can academic projects and Wikidata be mutually enriching, given the different systems of validation and recognition that operate within each other? While many Wikidata editors have deep expertise, the platform's structure is built on principles of openness, peer consensus, and collaborative editing rather than formal academic credentials. In contrast, academia tends to associate authority with disciplinary expertise, institutional affiliation, and scholarly output. Similarly, institutions such as governments or GLAM organizations are often recognized as authoritative because of their perceived reliability and structured oversight. These different frameworks can create asymmetries in how contributions are valued and trusted: while academia often operates through top-down models of validation, collaborative platforms like Wikidata rely more on distributed forms of consensus. Understanding and negotiating these differences is key to enhance productive dialogue and collaboration between the two ecosystems.
<!--
This brings us to a central question: how can academic projects and Wikidata benefit from one another when unequal hierarchies of authority persist between these platforms? Indeed, there is a clear distinction between contributions from experts --- scholars, government bodies, or institutions --- and those from non-experts, such as general Wikidata editors. In academia, authority is frequently equated with expertise and influence, recognized and exerted within the boundaries of specific disciplines. Outside academia, institutions such as governments or GLAM organizations are similarly perceived as authoritative sources. Within any scholarly domain, certain individuals --- by means of influential publications or institutional standing --- are considered the custodians of knowledge. This interpretation of the authoritative figure typically establishes a *top-down hierarchy* that privileges traditional producers of knowledge --- positioning them as its sole custodians. --> 
<!-- @max : un peu changé ici, ok ?-->

We argue, however, that this top-down hierarchy model is contextual and not always best suited for knowledge dissemination, particularly in the case of digital platforms. As collaborative, crowdsourced, and peer-contributed infrastructures like Wikidata increasingly assert themselves as alternative forms of authority --- both within and beyond academia --- they challenge conventional assumptions about data reliability and the garanty of expertise. This is mainly due to the fact that, in most cases, anyone can contribute to these platforms, leading some to question the quality of the data [@Santos24].

The status of Wikidata editors as authoritative actors is therefore often questioned. Many scholars and professionals consider them to be *amateurs* rather than experts.^[We define *amateur* as a socially engaged, non-professional actor who contributes to cultural, artistic or documentary activities outside formal institutional structures --- often through participatory digital platforms. This figure is typically characterised by a high degree of self-taught expertise, an individual pursuit of excellence, a paradoxical sociability rooted in both emancipation and community, and a privileged relationship with digital platforms as new spaces of recognition and knowledge production. On the evolution of the term, see @severoLimperatifParticipatifInstitutions2021.] Despite the increasing involvement of non-professionals in cultural initiatives, especially online, their contributions often remain undervalued or require validation by recognised professionals to be considered reliable. This tension highlights the ambiguous relationship between new actors in knowledge creation and traditional epistemic authorities who are still unsure about how to integrate them. 

In Wikidata, this dynamic manifests in conflicting perceptions of authority. While the platform is designed to support collaborative knowledge production and open participation, its data is frequently considered trustworthy only when curated or approved by recognized experts. Yet, recent studies suggest that although Wikidata still has room for improvement, the platform is increasingly being recognised as a high-quality knowledge graph --- one whose quality depends on context and must be assessed on a case-by-case basis [@piscopoWhatWeTalk2019; @shenoyStudyQualityWikidata2022; @zhaoSystematicReviewWikidata2023]. The platform's growing and active community contributes significantly to its data quality, while tools such as Shape Expressions (ShEx) Schemas are being implemented to enforce model conformity and internal consistency [see @thorntonUsingShapeExpressions2019; @thorntonEncodingArchaeologicalData2024].^[Shape Expressions (ShEx) are a formal language used to describe and validate the structure of RDF data. In Wikidata, ShEx Schemas help ensure that items conform to expected data models by defining required properties and value types.] These community-driven standards not only support data consistency but also reflect the platform's commitment to a decentralized yet structured form of knowledge governance. 

One of the most effective ways to ensure the quality and relevance of Wikidata is not only to assess it from the outside, but rather to engage directly with it. Through engagement with the platform --- making statements, creating data models, correcting mistakes, and discussing over ontologies --- researchers, cultural institutions and engaged amateurs alike help to shape the platform and its knowledge graph. Wikidata is not a finished product to be critiqued, but an open, iterative space where quality emerges through collective interaction.

Another way to reconceptualise authority in DH projects is to integrate Wikidata not only as a reference point, but as a core infrastructural layer for data modelling, curation and publication. In this way, the authoritative role traditionally held by academic experts is distributed and shared with a broader community of Wikidata contributors. Authority is thus reframed --- not as a fixed attribute derived from institutional status, but as an emergent property of collaborative practices. Such reframing invites researchers to reconsider their own position --- not above or outside the platform, but alongside a distributed network of contributors who collectively construct meaning, value, and trust in data.

In order to examine these dynamics more thoroughly, we now turn to our case study: the *AG* project. We will examine how the project builds its digital infrastructure around Wikidata, collective intelligence and participatory practices to challenge and reshape the status of authoritative figures within academic knowledge production.

## A collaborative and digital edition of the *Greek Anthology* 

Since 2014, Marcello Vitali-Rosati and his team have been developing a digital and collaborative edition of the *Greek Anthology* [@verstraetePassesPresentsAnthologiques2024; @verstraete2024; @vitali-rosatiLepopeeNumeriqueLAnthologie2021; @mellet2020; @vitali-rosatiEditorializingGreekAnthology2020]. The project was born out of the need to index and render accessible this foundational corpus, which gathers nearly all the known epigrams of ancient Greek literature. From the beginning, the aim was not only to provide access to these texts, but also to experiment with a digital editorial model suited to their fragmentary nature and complex transmission history. 

Early stages of the project focused on exploring how digital tools could enhance both access to and understanding of that material. Our first prototype --- a SPIP-based website --- provided a foundation for collaborative enrichment and allowed us to begin identifying the technical and hermeneutic challenges of such an edition.

These early experiments revealed that designing a digital edition involves more than providing access to texts [@sahle_2016]: it requires a coherent epistemological model to organize the relationships among texts, editions, translations, annotations, and contributors. As the project progressed, the platform evolved to support collaborative editing, allowing users to contribute translations, metadata, and commentary: that is when the platform [*Anthologia Palatina*](https://anthologia.ecrituresnumeriques.ca/home) was created. Yet, as the corpus expanded and new contributors joined, the limits of the initial infrastructure --- particularly in terms of multilingual support and stable identification of entities --- became increasingly apparent.

In response, a last platform was developed: [Anthologia Graeca]((https://anthologiagraeca.org/)), augmented by an [API](https://preprod.anthologiagraeca.org/api/), and based on a backend architecture implemented in Django, a Python-based web framework. 
Through the contributions of a wide range of collaborators, the platform offers a rich set of information for each epigram. Each epigram is presented on a dedicated page, where one can access (1) its location in the *Palatine* manuscript (the *codex Palatinus graecus* 23, the principal testimony for the *Palatine Anthology*), retrieved via the IIIF protocol through the Heidelberg Library’s annotation tool linked to its API^[See [Heidelberg, Universitätsbibliothek, *Pal. gr.* 23](http://digi.ub.uni-heidelberg.de/diglit/cpgraec23). The final folios of the manuscript (615-709) are held at the BNF, under the shelfmark [*Paris. Suppl. gr.* 384](https://gallica.bnf.fr/ark:/12148/btv1b8470199g/) ; they are not yet integrated into the platform.], (2) multiple translations in various languages, (3) various keywords (author, cities and other thematic keywords), (3) commentaries, (4) internal and external references, and (5) cross-alignments between translations.

This iteration emphasized interoperability and collaboration, aligning with core principles of the Digital Classics community. Partnerships --- with initiatives such as Perseus, Perseids, the Heidelberg Library, or the *Liceo Classico Cagnazzi* (Altamura, Bari) --- highlight the project’s orientation toward open scholarship and cultural heritage valorization. The editorial model was also refined: the epigram became the fundamental editorial unit, and the platform adopted a semantic web approach grounded in the systematic use of Wikidata identifiers^[All data from previous platforms were automatically imported, although not all entities are yet linked to Wikidata --- this reconciliation is ongoing, but reveals some epistemological problems (see *infra*). <!--The platform reflects a dynamic editorial philosophy: one that is open, decentralized, and integrated into the broader ecosystem of digital knowledge production.--> Importantly, the project is unfinished --- and necessarily so. This is not simply due to the usual incompleteness of digital infrastructure, but because of the anthology’s very nature: a form that resists closure. New readings, translations, annotations, and interconnections will always be possible. While nearly all epigrams are already available online, some remain unfinished, and others await transcription or metadata enrichment. Annotation, translation, and semantic linking --- particularly through Wikidata --- open up a boundless field of contribution. The platform is designed to remain open, both structurally and epistemologically, to future layers of meaning and interpretation.<!--peut-être qu'il faut remonter ça dans le texte principal, peut-être plus bas.-->]. The adoption of Wikidata thus marks a significant turn in the project’s editorial framework. It addresses long-standing challenges around entity disambiguation and contributes to embedding each editorial act within a federated, multilingual knowledge network. This choice also reaffirms the project’s original ambition: to develop a truly collaborative and open-ended editorial model.

This case-study focuses specifically on the project's use of keywords --- covering entities such as (a) authors, (b) cities, and (c) others keywords collections divided in sections like deities, epithets, and epiclesis ; [the full list can be found on the website](https://anthologiagraeca.org/keywords/). In the course of the platform’s development, it was decided that each keyword must be linked to Wikidata: any new keyword must be associated with a corresponding Wikidata identifier. This editorial choice initiated a comprehensive reconciliation of the platform’s metadata with the Wikidata knowledge base.

### The Authors of the *Greek Anthology*

From the new platform onwards, adding a Wikidata URI became a requirement for creating any new keyword. This decision, however, left a large portion of previously imported keywords unreconciled --- particularly thematic motifs, cited personas, and editorial constructs (see *infra*). To address this, we launched a broader reconciliation effort, beginning with the authors, as they appeared to be both the most central and the most straightforward category to align with Wikidata. This assumption turned out to be only partly correct. While some authors could be easily matched, others presented more complex challenges.

On a methodological point of view, we started by exporting all author names from our platform into a CSV file, which served as both a diagnostic tool and a working basis for reconciliation. We matched names to existing Wikidata entities when possible, flagged ambiguous or missing entries, and created new ones when necessary. For each entry, we aimed to ensure multilingual labels (Latin, French, English, Italian, Ancient Greek). Even at this early stage, we encountered various issues: some errors in our database (e.g., Phanias), duplicate or ambiguous entries (e.g., Diodorus), and uncertain attributions for common names (e.g., Dionysios, Archias). We undertook the philological work of identifying and disambiguating these entries, and then pushed the revised dataset to Wikidata using OpenRefine.

The response from the Wikidata community was immediate and enlightening. Editors quickly pointed out methodological issues and helped correct errors, as documented [in a discussion about our contribution](https://www.wikidata.org/wiki/User_talk:Enrico_malatesta#Epigrammatistes). Some errors highlighted our lack of familiarity with Wikidata conventions, and sparked further discussion about how to prevent such problems (such as [preventing the ability to overwrite existing labels and aliases](https://phabricator.wikimedia.org/T157774)). This process revealed both the strength of the Wikidata community and our own limitations.

Eventually, we re-imported the cleaned data into our platform directly from Wikidata.

Beyond the technical outcome, the process also triggered deeper editorial decisions. Several problematic or overlapping attributions had to be revisited and clarified through philological research. Below, we present a few representative cases that illustrate the nature and complexity of this work.

Eventually, we retrieved the data from Wikidata and added it to our platform. This effort led not only to technical improvements, but also to critical editorial interventions. Many cases of dubious or overlapping attributions had to be revisited and clarified through philological research. Below are a few representative examples that illustrate the complexity of this work. 

<!--
:::{.callout-important}
## TO DO  
- Pluarality of facts : Möller, C., Lehmann, J., Usbeck, R., . Survey on english entity linking on wikidata. 
- Beek, W., Rietveld, L., Bazoobandi, H.R., Wielemaker, J., Schlobach, S., 2014. Lod laundromat: a uniform way of publishing other people’s dirty data, in: International semantic web conference, Springer. pp. 213–228.
- Who Models the World?: Collaborative Ontology Creation and User Roles in Wikidata -> many kind of user in ps-lucian by ex. 
:::
--> 

#### Phanias

This work allwed us to spot errors made in our platform. For example, our data listed two authors under the name Phanias: "Phanias" (*Eresius*, [TLG-1578](urn:cts:greekLit:tlg1578)) and "Phanias" (*Epigrammaticus*, [TLG-1582](urn:cts:greekLit:tlg1582)). According to Gow and Page [-@gow_greek_1965, 464-475], as well as in the Budé edition [@waltz_anthologie_1929], all extant epigrams should be attributed to the latter. The former, while historically attested, was erroneously credited due to editorial confusion. We corrected this by attributing all epigrams to the appropriate Phanias and updating our metadata accordingly.

#### Diodoros

Our database initially contained 4 variants of the name Diodoros: “Diodorus, Diodoros”, “Diodore de Tarse, Diodoros le Grammairien”, “Diodoros Zonas de Sardes”, and a lowercase entry, “diodorus”. In the Budé edition of the *Greek Anthology* several individuals are recognized under this name : 

> *Diodoros*. Trois poètes de la Couronne de Philippe ont porté ce nom : Diodore Zonas, de Sardes, orateur célèbre du temps de la guerre de Mithridate ; un autre Diodoros de Sardes ; enfin, Diodoros de Tarse. On ne sait auquel attribuer les épigrammes où le gentilicium n’est pas spécifié. [@waltz_anthologie_2003, 142-143]

We reconcile this data with Perseus and kept three distinct *Diodorus* in our database : [Diodorus of Sardis](urn:cts:greekLit:tlg0165), [Diodorus Zonas](urn:cts:greekLit:tlg0164), [Diodorus of Tarsus](urn:cts:greekLit:tlg0166), along with a *catch-all* ["Diodoros Epigrammaticus"](urn:cts:greekLit:tlg0163) for unattributed or conflated cases. The label "Epigrammaticus" was adopted (in line with Perseus conventions) for clarity, although it artificially unifies what are likely separate historical individuals. Where the manuscript tradition does not specify a gentilicium or distinguishing epithet, this pragmatic solution provides a stable point of reference.

#### Dionysios

The case of Dionysios illustrates the difficulties posed by common names in the manuscript tradition. Next to several epigrams, we find the simple attribution "Διονυσίου" (of Dionysios) without further clarification. Gow and Page [-@gow_greek_1965, 231] note that the name Dionysios is extremely common, and there is no internal evidence to determine how many distinct authors are represented in the *Greek Anthology*. Given this uncertainty, we retained existing individual Dionysios when information allowed ([Dionysius of Andros](urn:cts:greekLit:tlg0168), [Dionysius of Cyzicus](urn:cts:greekLit:tlg0169), [Dionysius of Rhodes](urn:cts:greekLit:tlg0170) and [Dionysius the Sophist](urn:cts:greekLit:tlg0171)), and introduced a generic ["Dionysius"](urn:cts:greekLit:tlg0167) entity for epigrams with unresolved attribution. It is not a perfect solution, and it does not claim to resolve the uncertainty --- but it does allow us to surface that uncertainty clearly, rather than pretending it does not exist. In that sense, it follows the same logic we adopted for the Diodoros entries: not trying to solve an unsolvable problem, but giving it space to be visible and documented. This raises the question of "how do we make ambiguity and uncertainty readable, especially in a digital context?"<!-- common names--> 

#### Archias

Finally, the name Archias presented one of the most tangled cases. Our platform originally grouped all entries under a single name, aggregating multiple forms "Archias, Archias d’Antioche, Archias de Byzance, Archias de Macédoine, Archias de Mytilène, Archias of Macedon, Archias of Mytilene". Perseus lists a general “Archias the Epigrammatist” ([TLG-0126](urn:cts:greekLit:tlg0126)). Wikidata likewise has an entry for ["Archias the Epigrammatist"](https://www.wikidata.org/wiki/Q80207093) which redirects to more specific entities where available. *Aulius Licinius Archias*, the subject of Cicero’s *Pro Archia*, is distinct both on [Perseus](urn:cts:greekLit:tlg0127) and on [Wikidata](https://www.wikidata.org/wiki/Q218251).

The Budé editions add further complexity, identifying five different individuals under the name Archias, across various volumes:

- Archias of Antioch, also identified as A. Licinius Archias [@waltz_anthologie_2003, 141; @waltz_anthologie_1931, 184; @waltz_anthologie_1960, 175; @waltz_anthologie_1974, 281; @irigoin_anthologie_2017, 69; @aubreton_anthologie_1980, 302]; 
- Archias of Byzantium, attributed to the *Garland of Philip* [@waltz_anthologie_1960, 175]; 
- Archias of Macedon, whose very existence is contested [@waltz_anthologie_1960, 175]; 
- Archias of Mytilene, possibly contemporary with Archias of Antioch [@waltz_anthologie_1960, 175; @waltz_anthologie_1974, 281]; 
- Archias the Younger, a poorly known poet from the *Garland of Philip*, possibly the same as Archias of Antioch [@waltz_anthologie_1974, 281; @irigoin_anthologie_2017, 69].

To complicate matters further, Gow and Page, discussing epigrams attributed to "Archias of Byzantium", introduce yet another figure, "Archias Grammaticus":

> Archias Grammaticus may be a different person from, or the same person as, the Byzantine; we simply do not know. [-@gow_greek_1965, 434-435]

Faced with this level of ambiguity, we adopted a layered model: creating distinct Wikidata entries for historically or textually identifiable individuals, and adding disambiguation notes within our platform for uncertain or overlapping cases. This approach allows us to remain consistent with scholarly conventions while aligning with established infrastructures (TLG, Perseus, Wikidata).

### Some comments on the outcome and future work 

The reconciliation work between the *AG* platform and Wikidata --- initiated as a metadata cleaning project --- has led to substantial improvements across our platform. We clarified and corrected numerous author attributions, inserted inline commentary where attribution remains uncertain (e.g., [*AG* 10.38](https://anthologiagraeca.org/passages/urn:cts:greekLit:tlg7000.tlg001.ag:10.38/#comment-1087)), created new Wikidata entities for previously unlisted epigrammatists, and contributed multilingual labels. 

In undertaking this process, we have not only deepened the integration between philological expertise and semantic web technologies, but also brought to light a series of epistemological frictions and modeling challenges --- revealing the extent to which editorial categories, rooted in interpretive scholarship, can resist or complicate their translation into structured, ontological frameworks like Wikidata. A particularly revealing case involved the labeling of pseudo-authors in Ancient Greek ([see our discussion on Pseudo-Lucian](https://www.wikidata.org/wiki/Talk:Q19558843#Nome_in_grc)). Indeed, in January 2023, a dialogue unfolded regarding whether pseudo-authors on Wikidata should be labeled in Ancient Greek, and if so, how. One of our imported entries --- initially labeled in Ancient Greek --- was removed due to concerns about accuracy and conceptual anachronism. The crux of the debate lay in whether the prefix Ψευδο- (as used in Modern Greek for pseudo-authors) should be applied to Ancient Greek labels. Some contributors noted that this construction appears rarely in ancient sources and argued that its use would introduce modern editorial assumptions into ancient naming practices.

Finally, further work must be done in order to reconcile other keywords. However, the reconciliation process is revealing several limitations and epistemological tensions between the platform’s existing editorial categories and the structure of Wikidata. Some keywords previously encoded in the *AG* platform do not align easily --- or meaningfully --- with Wikidata’s data model. For instance, certain categories were created specifically for earlier editorial experiments, namely the *Plateforme Ouverte des Parcours d'imaginaires* (POP) for which we added *reading path*-keywords such as *Animal's epitaph* ([on the AG platform](https://anthologiagraeca.org/keywords/232/) and on the [POP](https://pop.anthologiegrecque.org/#/parcours/308)) or *Deadly gifts* ([on the AG platform](https://anthologiagraeca.org/keywords/434/) and on the [POP](https://pop.anthologiegrecque.org/#/parcours/300)). Whether we need to include it in Wikidata is still unclear. 

Other keywords correspond to broader or more abstract concepts --- such as literary motifs or narrative structures --- that resist straightforward alignment with Wikidata entities (e.g. [*bad breath*](https://anthologiagraeca.org/keywords/253/) or [*drunkenness*](https://anthologiagraeca.org/keywords/85/)). In the case of cited individuals, the situation is even more complex: the *Greek Anthology* includes references to numerous figures whose historical existence is uncertain or contested. Reconciling these names would demand a sustained philological and prosopographical effort, as some may be fictional, mythological, or only attested within this corpus (we will not pursue this question here; see [@Floridi_2021] for broader epistemological considerations). In other cases, reconciliation is both feasible and necessary but requires careful, manual work --- especially for editorial categories such as the various epigrams collections (see, by example, the Garlands of [Meleager](https://anthologiagraeca.org/keywords/181/) or [Philip](https://anthologiagraeca.org/keywords/76/)) or cited poets. Overall, while the integration of Wikidata represents a significant step toward interoperability, the reconciliation of legacy data remains an ongoing process that highlights the complexity of mapping scientific knowledge to structured, external ontologies --- especially when retroactively aligning two editorial infrastructures that were not originally designed to work together.

<!--
### On co-existing informations and world visions 

:::{.callout-important}
## To add (?)
- Coexistence des informations ? 
- Diversité des visions du monde ? 

> peut-être exemplifier avec le label officiel pour les alternatives label ? (genre, "je veux que ma data soit le vrai label officiel et pas relégué à un label alternatif")
:::
--> 

## Conclusion 

Wikidata is not just a technical tool for data storage and retrieval; it is a dynamic epistemic space where academic knowledge is collaboratively shaped, revised, and legitimized. By delegating (while taking part of) some of our curatorial authority to Wikidata, the *AG* project participates in a broader shift towards distributed models of knowledge production [@benklerPeerProductionForm2015; @buchelerCrowdsourcingOpenInnovation2010]. This delegation does not imply an abandonment of academic rigor, but rather a reconfiguration of expertise --- one that recognizes the value of collective intelligence [@levyLintelligenceCollectivePour1994] and the potential of community-driven platforms to maintain high-quality, multilingual, and interoperable data [@surowieckiWisdomCrowdsWhy2004].

The implications of this shift are manifold. It invites researchers to rethink their role not only as producers of content, but also as facilitators of open, dialogical knowledge systems. It also raises critical questions: To what extent can academic standards be reconciled with the epistemological norms of a platform like Wikidata? How do we balance openness with accuracy, and participation with control? Far from erasing these tensions, the integration of Wikidata into our project foregrounds them --- and in doing so, creates an opportunity for scholars to collectively reflect on the processes of validation, authorship, and authority.

Ultimately, we suggest that embracing platforms like Wikidata means accepting that academic knowledge is always provisional, situated, and co-produced. It is a move toward a more resilient and plural form of scholarship - one that recognizes the potential of the many without losing sight of the responsibility of the few.


<!--
J'ai essayé de regrouper tout ça dans ma ccl. 

### On delegating the curation of academic data 

As this example shows, because we have chosen to involve a wider community as an authority figure, the *AG* project is no longer the sole custodian of its data. By delegating part of the curatorial process to Wikidata and its contributors, we embrace a model of distributed authority that challenges traditional academic hierarchies. This delegation implies a shift not only in who validates the data, but also in how validation itself is understood — no longer as a top-down, expert-driven process, but as a collective negotiation of meaning, relevance, and accuracy. 

This shift towards distributed authority has many implications. 

What are the implications of this shift toward distributed authority. How can that shift in authority benefit academic research projects? Is Wikidata’s epistemological paradigm coherent with ours? Can we think of a generic epistemological framework to be effectively applied to specific academic endeavors?

### Collective Intelligence

This approach echoes with broader theories of collective intelligence. Collective intelligence refers to the shared or group intelligent derived from collaboration, collective work, and competition among thousands of actors working together within a common setting. Within collective intelligence, the wisdom of the crowd is considered superior to individual or isolated intelligences [@surowieckiWisdomCrowdsWhy2004]. Platforms such as Wikidata embody the best case of how community decentralized work may lead towards generating structured quality knowledge --- provided that the contributions are supported by transparent rules, mechanisms of coordination, and mutual trust among contributors [@benklerPeerProductionForm2015; @buchelerCrowdsourcingOpenInnovation2010].

As Pierre Lévy argues, collective intelligence is especially interesting and valuable for digital environments [@levyLintelligenceCollectivePour1994]. Collaborative digital platforms are not about homogenizing knowledge or erasing differences in expertise, but about creating a space where knowledge can circulate, evolve, and converge through dialogue and participation. In Wikidata, this manifests through talk pages, project discussions, creation or modification of items and properties, and the continuous negotiation of meanings across languages, cultures, and disciplinary boundaries. It is through this ongoing process that the authority and legitimacy of the platform are constructed --- not imposed from above, but co-produced by its users.

## Conclusion 

We suggest that Wikidata is not merely a technical tool but rather a space where methodological and epistemological debates can unfold. By engaging with this dynamic, researchers can enhance their projects while contributing to the creation of a more sustainable, inclusive, and collaborative knowledge base.

-->
<!--
:::{.callout-important}
## To add 

- our presentation invites reflection on the implications of this shift toward distributed authority. 
- How can that shift in authority benefit academic research projects? 
- Is Wikidata’s epistemological paradigm coherent with ours? 
- Can we think of a generic epistemological framework to be effectively applied to specific academic endeavors?
:::
--> 
## References